podcast/blueprints/authentication.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from ..authentication.authentication import RegistrationForm, LoginForm
from podcast.authentication.services import auth_services
from podcast.blueprints.services import *

authentication_blueprint = Blueprint(
    'authentication_bp', __name__)

@authentication_blueprint.route('/authentication/register', methods=['GET', 'POST'])
def register():
    authentication_type = "Register"
    form = RegistrationForm()
    repo_instance = get_repo()

    if form.validate_on_submit():
        if not auth_services.user_registered(form.username.data, repo_instance): # --------------------------------------
            auth_services.register_user(form.username.data, form.password.data, repo_instance) # --------------------------------------
            session.clear()
            session['username'] = form.username.data
            print(f"Registered and logged in as {form.username.data}")
            return redirect(url_for('home_bp.home'))
        else:
            print("Username already exists!")

    return render_template('authentication.html',
                           auth_type=authentication_type, form=form)


@authentication_blueprint.route('/authentication/login', methods=['GET', 'POST'])
def login():
    repo_instance = get_repo()
    authentication_type = "Login"
    form = LoginForm()

    # Checks if username exists in Memory Repository, password check is in LoginForm
    if form.validate_on_submit():
        if auth_services.user_registered(form.username.data, repo_instance): # --------------------------------------
            if auth_services.authenticate_user(form.username.data, form.password.data, repo_instance): # --------------------------------------
                session.clear()
                session['username'] = form.username.data
                return redirect(url_for('home_bp.home'))
        else:
            print("Incorrect Username or Password!")
        return redirect(url_for('authentication_bp.login'))

    return render_template('authentication.html',
                           auth_type=authentication_type, form=form)


@authentication_blueprint.route('/authentication/logout')
def logout():
    session.clear()
    users = get_users() # --------------------------------------
    print(users)
    return redirect(url_for('home_bp.home'))

podcast/blueprints/catalogue.py
from flask import Blueprint, render_template, request
from podcast.authentication.services import auth_services
from podcast.blueprints.services import *

catalogue_blueprint = Blueprint(
    'catalogue_bp', __name__)


@catalogue_blueprint.route('/podcasts', methods=['GET'])
def catalogue():
    username = auth_services.get_current_username()
    podcasts = get_podcasts_by_name() # --------------------------------------

    per_page = 10
    total_pages = (len(podcasts) + per_page - 1) // per_page
    page = request.args.get('page', 1, type=int)

    # Takes podcasts depending on page number
    start = (page - 1) * per_page
    end = start + per_page
    items_on_page = podcasts[start:end]

    return render_template('catalogue.html', items_on_page=items_on_page,
                           total_pages=total_pages, page=page, username=username)

podcast/blueprints/playlists.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from podcast.blueprints.services import *
from podcast.domainmodel.model import Playlist

playlists_blueprint = Blueprint(
    'playlists_bp', __name__)


@playlists_blueprint.route('/playlists', methods=['GET', 'POST'])
def playlists():
    if 'username' not in session:
        return redirect(url_for('authentication_bp.login'))

    user = get_user(session['username']) # --------------------------------------
    user_playlists = get_playlists_by_user(user) # --------------------------------------

    return render_template('playlists.html', playlists=user_playlists, username=session['username'])


@playlists_blueprint.route('/playlists/create', methods=['GET', 'POST'])
def create_playlist():
    if 'username' not in session:
        return redirect(url_for('authentication_bp.login'))

    user = get_user(session['username']) # --------------------------------------
    if request.method == 'POST':
        playlist_name = request.form.get('playlist_name')
        if playlist_name:
            playlist_id = get_next_playlist_id() # --------------------------------------
            new_playlist = Playlist(playlist_id=playlist_id, playlist_name=playlist_name, user=user)
            add_playlist(new_playlist) # --------------------------------------
            return redirect(url_for('playlists_bp.playlists'))


@playlists_blueprint.route('/playlists/add_podcast/<int:podcast_id>', methods=['GET','POST'])
def add_podcast_to_playlist(podcast_id):
    if 'username' not in session:
        return redirect(url_for('authentication_bp.login'))

    playlist_id = request.form.get('playlist_id')
    playlist = get_playlist(int(playlist_id)) # --------------------------------------
    podcast = get_podcast(podcast_id) # --------------------------------------

    if playlist and podcast:
        playlist.add_podcast(podcast)
        save_playlist(playlist) # --------------------------------------
    return redirect(url_for('podcast_description_bp.podcast_description', podcast_id=podcast_id))


@playlists_blueprint.route('/playlists/add_episode/<string:episode_title>', methods=['GET','POST'])
def add_episode_to_playlist(episode_title):
    if 'username' not in session:
        return redirect(url_for('authentication_bp.login'))

    playlist_id = request.form.get('playlist_id')
    podcast_id = request.form.get('podcast_id')
    playlist = get_playlist(int(playlist_id)) # --------------------------------------
    episode = get_episode_by_title(episode_title) # --------------------------------------
    playlist.playlist_add(episode) # --------------------------------------
    save_playlist(playlist) # --------------------------------------

    return redirect(url_for('podcast_description_bp.podcast_description', podcast_id=podcast_id))


@playlists_blueprint.route('/playlists/remove_podcast/<int:playlist_id>/<string:podcast_title>', methods=['POST'])
def remove_podcast_from_playlist(playlist_id, podcast_title):
    if 'username' not in session:
        return redirect(url_for('authentication_bp.login'))

    user = get_user(str(session['username'])) # --------------------------------------
    playlist = get_playlist(playlist_id) # --------------------------------------

    if playlist and playlist.user == user:
        podcast = get_podcast_by_title(podcast_title) # --------------------------------------
        if podcast:
            playlist.remove_podcast(podcast)
            save_playlist(playlist) # --------------------------------------

    return redirect(url_for('playlists_bp.playlists'))

@playlists_blueprint.route('/playlists/remove_episode/<int:playlist_id>/<string:episode_title>', methods=['POST'])
def remove_episode_from_playlist(playlist_id, episode_title):
    if 'username' not in session:
        return redirect(url_for('authentication_bp.login'))

    user = get_user(session['username']) # --------------------------------------
    playlist = get_playlist(playlist_id) # --------------------------------------
    if playlist and playlist.user == user:
        episode = get_episode_by_title(episode_title) # --------------------------------------
        if episode:
            playlist.remove_episode(episode)
            save_playlist(playlist) # --------------------------------------

    return redirect(url_for('playlists_bp.playlists'))

podcast/blueprints/podcast_description.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from podcast.domainmodel.model import Review
from podcast.authentication.services import auth_services
from podcast.blueprints.services import *

podcast_description_blueprint = Blueprint(
    'podcast_description_bp', __name__)


@podcast_description_blueprint.route('/description/<int:podcast_id>', methods=['GET', 'POST'])
def podcast_description(podcast_id):
    username = auth_services.get_current_username()
    podcast = get_podcast(podcast_id) # --------------------------------------
    print(podcast)
    episodes = get_episodes_for_podcast(podcast_id) # --------------------------------------

    per_page = 5
    total_pages = (len(episodes) + per_page - 1) // per_page
    page = request.args.get('page', 1, type=int)

    start = (page - 1) * per_page
    end = start + per_page
    items_on_page = episodes[start:end]

    # Review

    if request.method == "POST":
        if 'username' not in session:
            return redirect(url_for('authentication_bp.login')) # redirect to login page
        user = get_user(session['username']) # --------------------------------------
        rating = request.form.get('rating', type=int)
        content = request.form.get('content')

        # Make a review and save it for the session
        review = Review(review_id=get_length()+1, user=user, rating=rating, content=content, podcast_id=podcast_id)
        #podcast.reviews.append(review)

        save_review(review)
        return redirect(url_for('podcast_description_bp.podcast_description', podcast_id=podcast_id))

    average_rating = sum([review._rating for review in get_review(podcast_id)]) / len(get_review(podcast_id)) if get_review(podcast_id) else 0
    sorted_reviews = sorted(get_review(podcast_id), key=lambda x: x._rating, reverse=True)
    user_playlists = []
    if 'username' in session:
        user = get_user(session['username']) # --------------------------------------
        user_playlists = get_playlists_by_user(user) # --------------------------------------

    return render_template('podcastDescription.html', podcast=podcast,
                           episodes=episodes,
                           items_on_page=items_on_page,
                           total_pages=total_pages, page=page,
                           average_rating=average_rating,podcast_id=podcast_id, reviews=sorted_reviews,
                           user_playlists=user_playlists, username=username)

podcast/blueprints/search_query.py
from flask import Blueprint, render_template, request
from podcast.utilities.services import search_by_podcast_name, search_by_author_name, search_by_category
from podcast.authentication.services import auth_services
from podcast.blueprints.services import *


catalogue_blueprint = Blueprint(
    'search_query_bp', __name__)


@catalogue_blueprint.route('/search', methods=['GET', 'POST'])
def search():
    username = auth_services.get_current_username()
    query = request.args.get('query', '')
    parameter = request.args.get('parameter', 'Title')
    repo_instance = get_repo()
    if parameter == "Author":
        podcasts = search_by_author_name(query, repo_instance) # --------------------------------------
    elif parameter == "Category":
        podcasts = search_by_category(query, repo_instance) # --------------------------------------
    else:
        podcasts = search_by_podcast_name(query, repo_instance) # --------------------------------------
        #Defaults to title if no parameter specified.

    per_page = 10
    total_pages = (len(podcasts) + per_page - 1) // per_page
    page = request.args.get('page', 1, type=int)

    # Takes podcasts depending on page number
    start = (page - 1) * per_page
    end = start + per_page
    items_on_page = podcasts[start:end]

    return render_template('catalogue.html', items_on_page=items_on_page,
                           total_pages=total_pages, page=page, username=username)

podcast/templates/authentication.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ auth_type }}</title>
    <link
        rel="stylesheet"
        href="../static/css/main.css"
    />
    <link rel="icon" href="../static/logo.png">
</head>
<body>
    <div id="body">
        {%  include 'navbar.html' %}
        <div id="content-2">
            <header id="header">
                <div class="copyright">&copy; hrol166 - kcam870 - kand684</div>
                {{ auth_type }}
            </header>

            <form method="POST">
                {{ form.hidden_tag() }}

                <div class="form-field">
                    {{ form.username.label(class="search-input") }} <br>
                    {{ form.username(class="search-container") }} <br>
                </div>

                <div class="form-field">
                    {{ form.password.label(class="search-input") }} <br>
                    {{ form.password(class="search-container") }} <br>
                </div>

                {{ form.submit(class="search-button") }}
            </form>

            {% if auth_type == "Register" %}
                <div>
                    Already have an account? Login <a href="{{ url_for('authentication_bp.login') }}"> Here. </a>
                </div>
            {% endif %}
            <div class="error-message">
                {% if form.password.errors %}
                {{ form.password.errors[0] }}
                {% else %}
                &nbsp;
                {% endif %}
            </div>
        </div>
    </div>
</body>
</html>

podcast/templates/catalogue.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Podcast Catalogue</title>
    <link
        rel="stylesheet"
        href="../static/css/main.css"
    />
    <link rel="icon" href="../static/logo.png">
</head>

<body>
{% include 'navbar.html'%}
    <div id="content-2">
        <header id="header">
              Our Podcasts
            <div class="copyright">&copy; hrol166 - kcam870 - kand684</div>
        </header>
            <main id="main">
                <div id="podcast-grid">
                    {% for podcast in items_on_page %}
                        <div class="podcast-item">
                            <a href="{{url_for('podcast_description_bp.podcast_description', podcast_id = podcast.id)}}">
                                <img src={{podcast.image}} alt="image">
                                    <div class="podcast-info">
                                        <h3>{{podcast.title}}</h3>
                                    </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
                <div class="pagination-container">
                    {%  if page > 1 %}
                    <a href="{{ url_for('catalogue_bp.catalogue', page=page-1) }}">
                        <img src="../static/Icons/chevron-left.svg" alt="previous" class="pagination-icon">
                    </a>
                    {% endif %}
                        <span> Page {{ page }} of {{ total_pages }}</span>
                    {% if page < total_pages %}
                    <a href="{{ url_for('catalogue_bp.catalogue', page=page+1) }}">
                        <img src="../static/Icons/chevron-right.svg" alt="next" class="pagination-icon">
                    </a>
                    {% endif %}
                </div>
            </main>
    </div>
</body>
</html>

podcast/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Overhear</title>
    <link
      rel="stylesheet"
      href="../static/css/main.css"
    />
    <link rel="icon" href="../static/logo.png">
</head>

<body>
    <div id="body">
        {% include 'navbar.html'%}
        <div id="content-2">
            <header id="header">
              Overhear
              <div class="copyright">&copy; hrol166 - kcam870 - kand684</div>
            </header>
                <div class="Welcome-paragraph">
                    Welcome to Overhear, a catalogue of some of the finest podcasts available. Browse some randomly assembled podcasts below, or head over to 'Podcasts' to view our entire selection.
                </div>
            <div id="container">
              <main id="main">
                <form action="{{ url_for('search_query_bp.search') }}" method="GET" class="search-container">
                    <input type="text" name="query" placeholder="Search Podcast..." class="search-input" required>
                    <select name="parameter" id="search-parameter">
                        <option value="Title">Title</option>
                        <option value="Author">Author</option>
                        <option value="Category">Category</option>
                    </select>

                    <button type="submit" class="search-button">Search</button>
                </form>
              </main>
            </div>
            <div id="podcast-grid">
              {% for podcast in podcasts %}
                <div class="podcast-item">
                  <a href="{{url_for('podcast_description_bp.podcast_description', podcast_id=podcast.id)}}">
                    <img src="{{podcast.image}}" alt="{{podcast.title}}">
                    <div class="podcast-info">
                      <h3>{{podcast.title}}</h3>
                      <p>{{podcast.get_pleasant_categories()}}</p>
                    </div>
                  </a>
                </div>
              {% endfor %}
            </div>
        </div>
    </div>
</body>
</html>

podcast/templates/navbar.html
<nav>
    <img id="logo" src="../static/logo.png" />
    <div class="heading">Overhear</div>
    <div class="navbar">
        {% if username %}
            <h3 class="Welcome-paragraph" style="text-align: center;">
                Welcome {{ username }}!
            </h3>
        {% endif %}
        <ul>
            <li><a href="{{ url_for('home_bp.home') }}"> <img src="../static/Icons/home.svg" id="home-icon"> Home</a></li>
            <li><a href="{{ url_for('catalogue_bp.catalogue') }}"><img src="../static/Icons/headphones.svg" id="catalogue-icon"> Podcasts</a></li>
            <li><a href="{{ url_for('playlists_bp.playlists') }}"> <img src="../static/Icons/book-open.svg" id="playlist-icon"> My Playlists</a></li>
            <li><a href="#Account">
                <img src="../static/Icons/user.svg" id="user-icon" alt="Account Icon"> My Account</a>
            </li>
            {% if not username %}
            <li><a href="{{ url_for('authentication_bp.register') }}"> Register</a></li>
            <li><a href="{{ url_for('authentication_bp.login') }}"> Login</a></li>
            {% else %}
            <li><a href="{{ url_for('authentication_bp.logout') }}"> Logout</a></li>
            {% endif %}
        </ul>
    </div>
    <div id="nav-footer">
        CS235 hrol166 - kcam870 - kand684
    </div>
</nav>

podcast/templates/playlists.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Your Playlists</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>
<body>
    {% include 'navbar.html' %}

    <div id="content-2">
        <header id="header">
            My Playlists
            <div class="copyright">&copy; hrol166 - kcam870 - kand684 </div>
        </header>

        <div id="container">
            <main id="main">
                <form action="{{ url_for('playlists_bp.create_playlist') }}" method="POST">
                    <label for="playlist_name">Create a New Playlist:</label>
                    <input type="text" id="playlist_name" name="playlist_name" required>
                    <button type="submit">Create</button>
                </form>

                <h2>Your Playlists:</h2>
                {% for playlist in playlists %}
                    <div class="playlist">
                        <h3>{{ playlist._playlist_name }}</h3>
                        <p>Owner: {{ playlist._user.username }}</p>
                        <p>Podcasts in Playlist:</p>
                        <ul>
                            {% for pod in playlist.get_podcasts() %}
                                <li>{{ pod.title }}
                                    <form action="{{ url_for('playlists_bp.remove_podcast_from_playlist', playlist_id=playlist._playlist_id, podcast_title=pod) }}" method="POST" style="display:inline;">
                                        <button type="submit">Remove</button>
                                    </form>
                                </li>
                            {% endfor %}
                        </ul>
                        <p>Episodes in Playlist:</p>
                        <ul>
                            {% for epi in playlist.get_episodes() %}
                                <li>{{ epi.title }}
                                    <form action="{{ url_for('playlists_bp.remove_episode_from_playlist', playlist_id=playlist._playlist_id, episode_title=epi.title) }}" method="POST" style="display:inline;">
                                        <button type="submit">Remove</button>
                                    </form>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endfor %}
            </main>
        </div>
    </div>
</body>
</html>

podcast/templates/podcastDescription.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Podcast Description</title>
    <link
        rel="stylesheet"
        href="../static/css/main.css"
    />
    <link rel="icon" href="../static/logo.png">
</head>
<body>
    {% include 'navbar.html'%}
    <div id="content-2">
            <header id="header">
              {{podcast.title}}
              <div class="copyright">&copy; hrol166 - kcam870 - kand684 </div>
            </header>
            <div id="container">
              <main id="main">
                <div id="description">
                    <img src={{podcast.image}} alt="image">
                    <p><i>Author:</i> {{podcast.author}} </p>
                    <p><i>Language:</i> {{podcast.language}}</p>
                    <p><i>About:</i> {{podcast.description}}</p>
                    <p><i>Categories: </i> {{podcast.get_pleasant_categories()}} </p>
                    <p><i>Website: </i> {{podcast.website}} </p>
                    <p><i>iTunes ID: </i> {{podcast.itunes_id}} </p>
                    <p><i>Episodes: </i>
                        <ul>
                <!-- Code to generate each episode in podcast -->
                    {% for episode in items_on_page %}
                        <li>{{ episode.title }}
                            <form action="{{ url_for('playlists_bp.add_episode_to_playlist', episode_title=episode.title) }}" method="POST" style="display:inline;">
                                <input type="hidden" name="podcast_id" value="{{ podcast.id }}">
                                <input type="hidden" name="episode_title" value="{{ episode.title }}">

                                <select name="playlist_id" id="playlist_id">
                                    {% for playlist in user_playlists %}
                                        <option value="{{ playlist._playlist_id }}">{{ playlist._playlist_name }}</option>
                                    {% endfor %}
                                </select>
                                <button type="submit">Add Episode to Playlist</button>
                            </form>
                        </li>
                    {% endfor %}
                </ul>
                    </p>
                    {%  if page > 1 %}
                    <a href="{{ url_for('podcast_description_bp.podcast_description', podcast_id=podcast.id, page=page-1) }}">Previous  </a>
                {% endif %}
                    <span> Page {{ page }} of {{ total_pages }}</span>
                {% if page < total_pages %}
                <a href="{{ url_for('podcast_description_bp.podcast_description', podcast_id=podcast.id, page=page+1) }}">  Next</a>
                {% endif %}

                    <p>Average Rating: {{ average_rating }}/10</p>
                    <p>Reviews: </p>
                    <ul>
                        {% for review in reviews %}
                            <li>{{ username }}: {{ review.content }} (Rating: {{ review.rating }}/10)</li>
                        {% endfor %}
                    </ul>

                    <!-- Submit a review -->
                {% if session['username'] %}
                    <p>Leave a Review:</p>
                    <form method="post">
                        <label for="rating">Rating (0-10):</label>
                        <input type="number" name="rating" min="0" max="10" required>
                        <br>
                        <label for="content">Review:</label>
                        <textarea name="content" required></textarea>
                        <br>
                        <button type="submit">Submit Review</button>
                    </form>
                    <form action="{{ url_for('playlists_bp.add_podcast_to_playlist', podcast_id=podcast.id) }}" method="POST">
                        <input type="hidden" name="podcast_id" value="{{ podcast.id }}">

                        <select name="playlist_id" id="playlist_id">
                            {% for playlist in user_playlists %}
                                <option value="{{ playlist._playlist_id }}">{{ playlist._playlist_name }}</option>
                            {% endfor %}
                        </select>
                        <button type="submit">Add Podcast to Playlist</button>
                    </form>
                {% else %}
                    <p>Please <a href="{{ url_for('authentication_bp.login') }}">log in</a> or <a href="{{ url_for('authentication_bp.register') }}">Register</a> to leave a review.</p>
                    <!-- redirect to login page or register page -->
                {% endif %}

                </div>
              </main>
            </div>
  </div>
</body>
</html>